<a href="https://colab.research.google.com/github/ntomben97/NYC-Yellow-Taxi-Big-Data-Project/blob/main/Download_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Checking the original Data

In [ ]:
import requests
import pandas as pd

files = []

for year in range(2009, 2027):

    for month in range(1, 13):

        month_str = f"{month:02d}"

        url = (
            f"https://d37ci6vzurychx.cloudfront.net/"
            f"trip-data/yellow_tripdata_{year}-{month_str}.parquet"
        )

        try:
            response = requests.head(
                url,
                allow_redirects=True,
                timeout=10
            )

            # Print the response for newer years
            if year >= 2022:
                print(
                    f"{year}-{month_str}: "
                    f"HTTP {response.status_code} | "
                    f"Size: {response.headers.get('Content-Length', 'N/A')}"
                )

            if response.status_code == 200:

                size_bytes = int(
                    response.headers.get("Content-Length", 0)
                )

                if size_bytes > 0:

                    files.append({
                        "Year": year,
                        "Month": month,
                        "File": f"yellow_tripdata_{year}-{month_str}.parquet",
                        "Size_GB": size_bytes / (1024 ** 3),
                        "Size_Bytes": size_bytes
                    })

        except requests.RequestException as e:
            print(f"{year}-{month_str}: ERROR - {e}")

file_sizes = pd.DataFrame(files)

file_sizes



total_size_gb = file_sizes["Size_GB"].sum()

print(f"Number of files found: {len(file_sizes)}")
print(f"Total Yellow Taxi dataset size: {total_size_gb:.2f} GB")

2022-01: HTTP 200 | Size: 38139949
2022-02: HTTP 200 | Size: 45616512
2022-03: HTTP 200 | Size: 55682369
2022-04: HTTP 200 | Size: 55222692
2022-05: HTTP 200 | Size: 55558821
2022-06: HTTP 200 | Size: 55365184
2022-07: HTTP 200 | Size: 49367712
2022-08: HTTP 200 | Size: 49717159
2022-09: HTTP 200 | Size: 49619957
2022-10: HTTP 200 | Size: 57061938
2022-11: HTTP 200 | Size: 50106631
2022-12: HTTP 200 | Size: 53640739
2023-01: HTTP 200 | Size: 47673370
2023-02: HTTP 200 | Size: 47748012
2023-03: HTTP 200 | Size: 56127762
2023-04: HTTP 200 | Size: 54222699
2023-05: HTTP 200 | Size: 58654627
2023-06: HTTP 200 | Size: 54999465
2023-07: HTTP 200 | Size: 48361828
2023-08: HTTP 200 | Size: 48152353
2023-09: HTTP 200 | Size: 47895515
2023-10: HTTP 200 | Size: 59009059
2023-11: HTTP 200 | Size: 56094653
2023-12: HTTP 200 | Size: 56804275
2024-01: HTTP 200 | Size: 49961641
2024-02: HTTP 200 | Size: 50349284
2024-03: HTTP 200 | Size: 60078280
2024-04: HTTP 200 | Size: 59133625
2024-05: HTTP 200 | Size: 62553128
2024-06: HTTP 200 | Size: 59859922
2024-07: HTTP 200 | Size: 52299432
2024-08: HTTP 200 | Size: 51067350
2024-09: HTTP 200 | Size: 61170186
2024-10: HTTP 200 | Size: 64346071
2024-11: HTTP 200 | Size: 60658709
2024-12: HTTP 200 | Size: 61524085
2025-01: HTTP 200 | Size: 59158238
2025-02: HTTP 200 | Size: 60343086
2025-03: HTTP 200 | Size: 69964745
2025-04: HTTP 200 | Size: 67352824
2025-05: HTTP 200 | Size: 77837865
2025-06: HTTP 200 | Size: 73542954
2025-07: HTTP 200 | Size: 66943728
2025-08: HTTP 200 | Size: 62293743
2025-09: HTTP 200 | Size: 72432945
2025-10: HTTP 200 | Size: 75267589
2025-11: HTTP 200 | Size: 71134255
2025-12: HTTP 200 | Size: 73701327
2026-01: HTTP 200 | Size: 64165080
2026-02: HTTP 200 | Size: 58683353
2026-03: HTTP 200 | Size: 67891249
2026-04: HTTP 200 | Size: 64818115
2026-05: HTTP 200 | Size: 69699174
2026-06: HTTP 403 | Size: N/A
2026-07: HTTP 403 | Size: N/A
2026-08: HTTP 403 | Size: N/A
2026-09: HTTP 403 | Size: N/A
2026-10: HTTP 403 | Size: N/A
2026-11: HTTP 403 | Size: N/A
2026-12: HTTP 403 | Size: N/A
Number of files found: 209
Total Yellow Taxi dataset size: 29.96 GB

In [ ]:
yearly_sizes = (
    file_sizes
    .groupby("Year")["Size_GB"]
    .sum()
    .reset_index()
)

yearly_sizes.sort_values("Year", ascending=False)

    Year   Size_GB
17  2026  0.302919
16  2025  0.772973
15  2024  0.645408
14  2023  0.592082
13  2022  0.572856
12  2021  0.446644
11  2020  0.348873
10  2019  1.158130
9   2018  1.363844
8   2017  1.485167
7   2016  1.707174
6   2015  1.887845
5   2014  2.000711
4   2013  1.996676
3   2012  2.033804
2   2011  2.056566
1   2010  5.266181
0   2009  5.324814

In [ ]:
recent_years = yearly_sizes.sort_values("Year", ascending=False).copy()

recent_years["Cumulative_GB"] = recent_years["Size_GB"].cumsum()

recent_years

    Year   Size_GB  Cumulative_GB
17  2026  0.302919       0.302919
16  2025  0.772973       1.075892
15  2024  0.645408       1.721300
14  2023  0.592082       2.313383
13  2022  0.572856       2.886239
12  2021  0.446644       3.332883
11  2020  0.348873       3.681756
10  2019  1.158130       4.839886
9   2018  1.363844       6.203731
8   2017  1.485167       7.688898
7   2016  1.707174       9.396073
6   2015  1.887845      11.283918
5   2014  2.000711      13.284628
4   2013  1.996676      15.281304
3   2012  2.033804      17.315108
2   2011  2.056566      19.371674
1   2010  5.266181      24.637855
0   2009  5.324814      29.962669

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import requests
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed

BASE_URL = "https://d37ci6vzurychx.cloudfront.net/trip-data"

DOWNLOAD_DIR = Path(
    "/content/drive/MyDrive/MIT805/Group Project/src"
)

DOWNLOAD_DIR.mkdir(parents=True, exist_ok=True)

Mounted at /content/drive

In [ ]:

def download_file(year, month):
    month_str = f"{month:02d}"
    filename = f"yellow_tripdata_{year}-{month_str}.parquet"
    url = f"{BASE_URL}/{filename}"
    output_file = DOWNLOAD_DIR / filename

    if output_file.exists() and output_file.stat().st_size > 0:
        return f"Already exists: {filename}"

    try:
        response = requests.get(
            url,
            stream=True,
            timeout=(30, 300)
        )

        if response.status_code == 200:

            with open(output_file, "wb") as f:
                for chunk in response.iter_content(
                    chunk_size=8 * 1024 * 1024
                ):
                    if chunk:
                        f.write(chunk)

            size_mb = output_file.stat().st_size / (1024**2)

            return f"✓ {filename} ({size_mb:.1f} MB)"

        elif response.status_code == 404:
            return f"Not available: {filename}"

        else:
            return f"HTTP {response.status_code}: {filename}"

    except Exception as e:
        return f"ERROR {filename}: {e}"


# Create list of files to download
tasks = [
    (year, month)
    for year in range(2014, 2027)
    for month in range(1, 13)
]

# Download 4 files at a time
with ThreadPoolExecutor(max_workers=4) as executor:

    futures = [
        executor.submit(download_file, year, month)
        for year, month in tasks
    ]

    for future in as_completed(futures):
        print(future.result())

✓ yellow_tripdata_2014-01.parquet (164.0 MB)
✓ yellow_tripdata_2014-02.parquet (154.7 MB)
✓ yellow_tripdata_2014-04.parquet (174.7 MB)
✓ yellow_tripdata_2014-03.parquet (183.5 MB)
✓ yellow_tripdata_2014-07.parquet (157.5 MB)
✓ yellow_tripdata_2014-05.parquet (178.0 MB)
✓ yellow_tripdata_2014-08.parquet (165.2 MB)
✓ yellow_tripdata_2014-06.parquet (165.8 MB)
✓ yellow_tripdata_2014-09.parquet (175.3 MB)
✓ yellow_tripdata_2014-11.parquet (172.7 MB)
✓ yellow_tripdata_2014-12.parquet (170.7 MB)
✓ yellow_tripdata_2014-10.parquet (186.6 MB)
✓ yellow_tripdata_2015-02.parquet (163.7 MB)
✓ yellow_tripdata_2015-04.parquet (172.1 MB)
✓ yellow_tripdata_2015-03.parquet (176.8 MB)
✓ yellow_tripdata_2015-01.parquet (167.2 MB)
✓ yellow_tripdata_2015-06.parquet (163.8 MB)
✓ yellow_tripdata_2015-07.parquet (153.2 MB)
✓ yellow_tripdata_2015-08.parquet (147.1 MB)
✓ yellow_tripdata_2015-05.parquet (174.0 MB)
✓ yellow_tripdata_2015-10.parquet (163.2 MB)
✓ yellow_tripdata_2015-12.parquet (152.5 MB)
✓ yellow_tripdata_2016-02.parquet (150.8 MB)
✓ yellow_tripdata_2015-11.parquet (150.4 MB)
✓ yellow_tripdata_2015-09.parquet (149.2 MB)
✓ yellow_tripdata_2016-03.parquet (162.1 MB)
✓ yellow_tripdata_2016-06.parquet (149.0 MB)
✓ yellow_tripdata_2016-05.parquet (158.1 MB)
✓ yellow_tripdata_2016-01.parquet (144.2 MB)
✓ yellow_tripdata_2016-04.parquet (157.9 MB)
✓ yellow_tripdata_2016-07.parquet (137.9 MB)
✓ yellow_tripdata_2016-08.parquet (133.4 MB)
✓ yellow_tripdata_2016-09.parquet (135.3 MB)
✓ yellow_tripdata_2016-10.parquet (145.5 MB)
✓ yellow_tripdata_2016-11.parquet (134.6 MB)
✓ yellow_tripdata_2017-02.parquet (121.7 MB)
✓ yellow_tripdata_2017-03.parquet (137.9 MB)
✓ yellow_tripdata_2017-04.parquet (134.8 MB)
✓ yellow_tripdata_2016-12.parquet (139.2 MB)
✓ yellow_tripdata_2017-01.parquet (128.6 MB)
✓ yellow_tripdata_2017-05.parquet (135.8 MB)
✓ yellow_tripdata_2017-06.parquet (129.2 MB)
✓ yellow_tripdata_2017-09.parquet (121.0 MB)
✓ yellow_tripdata_2017-10.parquet (130.4 MB)
✓ yellow_tripdata_2017-08.parquet (113.1 MB)
✓ yellow_tripdata_2017-11.parquet (125.0 MB)
✓ yellow_tripdata_2017-12.parquet (128.0 MB)
✓ yellow_tripdata_2017-07.parquet (115.2 MB)
✓ yellow_tripdata_2018-01.parquet (117.9 MB)
✓ yellow_tripdata_2018-02.parquet (113.9 MB)
✓ yellow_tripdata_2018-03.parquet (127.4 MB)
✓ yellow_tripdata_2018-04.parquet (125.5 MB)
✓ yellow_tripdata_2018-06.parquet (118.4 MB)
✓ yellow_tripdata_2018-05.parquet (124.8 MB)
✓ yellow_tripdata_2018-07.parquet (107.0 MB)
✓ yellow_tripdata_2018-10.parquet (121.0 MB)
✓ yellow_tripdata_2018-11.parquet (111.7 MB)
✓ yellow_tripdata_2018-12.parquet (112.4 MB)
✓ yellow_tripdata_2018-08.parquet (106.3 MB)
✓ yellow_tripdata_2018-09.parquet (110.2 MB)
✓ yellow_tripdata_2019-01.parquet (105.3 MB)
✓ yellow_tripdata_2019-02.parquet (98.6 MB)
✓ yellow_tripdata_2019-03.parquet (110.6 MB)
✓ yellow_tripdata_2019-04.parquet (105.0 MB)
✓ yellow_tripdata_2019-05.parquet (106.3 MB)
✓ yellow_tripdata_2019-08.parquet (85.8 MB)
✓ yellow_tripdata_2019-07.parquet (89.5 MB)
✓ yellow_tripdata_2019-09.parquet (92.6 MB)
✓ yellow_tripdata_2019-11.parquet (96.2 MB)
✓ yellow_tripdata_2019-10.parquet (101.4 MB)
✓ yellow_tripdata_2019-12.parquet (96.4 MB)
✓ yellow_tripdata_2020-03.parquet (42.4 MB)
✓ yellow_tripdata_2020-01.parquet (89.2 MB)
✓ yellow_tripdata_2020-04.parquet (4.2 MB)
✓ yellow_tripdata_2020-02.parquet (87.9 MB)
✓ yellow_tripdata_2019-06.parquet (98.1 MB)
✓ yellow_tripdata_2020-05.parquet (5.9 MB)
✓ yellow_tripdata_2020-07.parquet (12.8 MB)
✓ yellow_tripdata_2020-06.parquet (9.1 MB)
✓ yellow_tripdata_2020-08.parquet (15.8 MB)
✓ yellow_tripdata_2020-09.parquet (20.4 MB)
✓ yellow_tripdata_2020-10.parquet (25.1 MB)
✓ yellow_tripdata_2020-11.parquet (22.5 MB)
✓ yellow_tripdata_2020-12.parquet (22.0 MB)
✓ yellow_tripdata_2021-02.parquet (20.8 MB)
✓ yellow_tripdata_2021-03.parquet (28.6 MB)
✓ yellow_tripdata_2021-04.parquet (32.4 MB)
✓ yellow_tripdata_2021-05.parquet (36.9 MB)
✓ yellow_tripdata_2021-06.parquet (42.0 MB)
✓ yellow_tripdata_2021-07.parquet (41.7 MB)
✓ yellow_tripdata_2021-09.parquet (44.0 MB)
✓ yellow_tripdata_2021-10.parquet (50.8 MB)
✓ yellow_tripdata_2021-11.parquet (50.6 MB)
✓ yellow_tripdata_2021-12.parquet (47.3 MB)
✓ yellow_tripdata_2021-01.parquet (20.7 MB)
✓ yellow_tripdata_2021-08.parquet (41.4 MB)
✓ yellow_tripdata_2022-01.parquet (36.4 MB)
✓ yellow_tripdata_2022-03.parquet (53.1 MB)
✓ yellow_tripdata_2022-02.parquet (43.5 MB)
✓ yellow_tripdata_2022-05.parquet (53.0 MB)
✓ yellow_tripdata_2022-06.parquet (52.8 MB)
✓ yellow_tripdata_2022-07.parquet (47.1 MB)
✓ yellow_tripdata_2022-04.parquet (52.7 MB)
✓ yellow_tripdata_2022-08.parquet (47.4 MB)
✓ yellow_tripdata_2022-09.parquet (47.3 MB)
✓ yellow_tripdata_2022-10.parquet (54.4 MB)
✓ yellow_tripdata_2022-11.parquet (47.8 MB)
✓ yellow_tripdata_2023-01.parquet (45.5 MB)
✓ yellow_tripdata_2022-12.parquet (51.2 MB)
✓ yellow_tripdata_2023-02.parquet (45.5 MB)
✓ yellow_tripdata_2023-03.parquet (53.5 MB)
✓ yellow_tripdata_2023-04.parquet (51.7 MB)
✓ yellow_tripdata_2023-06.parquet (52.5 MB)
✓ yellow_tripdata_2023-05.parquet (55.9 MB)
✓ yellow_tripdata_2023-08.parquet (45.9 MB)
✓ yellow_tripdata_2023-09.parquet (45.7 MB)
✓ yellow_tripdata_2023-10.parquet (56.3 MB)
✓ yellow_tripdata_2023-12.parquet (54.2 MB)
✓ yellow_tripdata_2024-01.parquet (47.6 MB)
✓ yellow_tripdata_2024-03.parquet (57.3 MB)
✓ yellow_tripdata_2023-07.parquet (46.1 MB)
✓ yellow_tripdata_2024-04.parquet (56.4 MB)
✓ yellow_tripdata_2024-02.parquet (48.0 MB)
✓ yellow_tripdata_2023-11.parquet (53.5 MB)
✓ yellow_tripdata_2024-05.parquet (59.7 MB)
✓ yellow_tripdata_2024-06.parquet (57.1 MB)
✓ yellow_tripdata_2024-07.parquet (49.9 MB)
✓ yellow_tripdata_2024-08.parquet (48.7 MB)
✓ yellow_tripdata_2024-09.parquet (58.3 MB)
✓ yellow_tripdata_2024-11.parquet (57.8 MB)
✓ yellow_tripdata_2024-10.parquet (61.4 MB)
✓ yellow_tripdata_2024-12.parquet (58.7 MB)
✓ yellow_tripdata_2025-01.parquet (56.4 MB)
✓ yellow_tripdata_2025-04.parquet (64.2 MB)
✓ yellow_tripdata_2025-03.parquet (66.7 MB)
✓ yellow_tripdata_2025-06.parquet (70.1 MB)
✓ yellow_tripdata_2025-02.parquet (57.5 MB)
✓ yellow_tripdata_2025-09.parquet (69.1 MB)
✓ yellow_tripdata_2025-05.parquet (74.2 MB)
✓ yellow_tripdata_2025-10.parquet (71.8 MB)
✓ yellow_tripdata_2025-07.parquet (63.8 MB)
✓ yellow_tripdata_2025-12.parquet (70.3 MB)
✓ yellow_tripdata_2025-08.parquet (59.4 MB)
✓ yellow_tripdata_2026-01.parquet (61.2 MB)
✓ yellow_tripdata_2025-11.parquet (67.8 MB)
✓ yellow_tripdata_2026-02.parquet (56.0 MB)
HTTP 403: yellow_tripdata_2026-06.parquet
HTTP 403: yellow_tripdata_2026-07.parquet
✓ yellow_tripdata_2026-03.parquet (64.7 MB)
HTTP 403: yellow_tripdata_2026-08.parquet
✓ yellow_tripdata_2026-04.parquet (61.8 MB)
HTTP 403: yellow_tripdata_2026-09.parquet
HTTP 403: yellow_tripdata_2026-10.parquet
HTTP 403: yellow_tripdata_2026-12.parquet
HTTP 403: yellow_tripdata_2026-11.parquet
✓ yellow_tripdata_2026-05.parquet (66.5 MB)